### ISSUE TITLE
Finalize site framework, deployment plan

### ISSUE THREAD

**Issue by chrismejia** [DosPlatinos/yoga-site#7]
# Task

- [ ] Decide which React framework you're using
- [ ] Decide where you're deploying to e.g. Netlify, Vercel
    - [ ] Confirm expected deploy costs, if any
    - [ ] Gather information of how to deploy project to desired service
- [ ] Confirm website domain details
    - [ ] What domain service you buying from/already have bought from

## AC

All tasks above are completed and programming can begin.
